"use client";
import {
  EventType,
  type AuthenticationResult,
  type EventMessage,
} from "@azure/msal-browser";
import { MsalProvider } from "@azure/msal-react";
import { Inter } from "next/font/google";
import { useRouter } from "next/navigation";
import { msalInstance } from "../auth-config";
import { CustomNavigationClient } from "../utils/navigation-client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Turborepo",
//   description: "Generated by create turbo",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  msalInstance.initialize().then(() => {
    msalInstance.addEventCallback((event: EventMessage) => {
      if (event.eventType === EventType.LOGIN_SUCCESS && event.payload) {
        const payload = event.payload as AuthenticationResult;
        msalInstance.setActiveAccount(payload.account);
      }
    });
  });
  const router = useRouter();
  const navigationClient = new CustomNavigationClient(router);
  msalInstance.setNavigationClient(navigationClient);
  return (
    <html lang="en">
      <body className={inter.className}>
        <MsalProvider instance={msalInstance}>{children}</MsalProvider>
      </body>
    </html>
  );
}
